services:
  - type: web
    name: chazefashion
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ChazeFashion.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ChazeFashion.settings
      - key: PYTHON_VERSION
        value: 3.9
